### ISSUE TITLE
Problem during install

### ISSUE THREAD

**Issue by cabrinoob** [vanng822/gps-util#2]
Install on wondows7 with node version v0.11.9 causing build error. 

Extract from npm-debug.log :

 ...
  pcre_byte_order.c
  pcre_maketables.c
  pcre_version.c
  pcre_study.c
  pcre_chartables.c
  pcre_newline.c
  pcreposix.c
  pcre_string_utils.c
  pcre_jit_compile.c
  pcre_ucd.c
  pcre_xclass.c
  libpcre.vcxproj -> C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_m
  odules\mmmagic\build\Release\\libpcre.lib
  magic.cc
C:\Users\fmeriot\.node-gyp\0.11.9\src\node.h(188): error C2146: erreur de syntaxe :
absence de ';' avant l'identificateur 'DecodeBytes' [C:\SVN\nodejs\sandbox\xml2json2
xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
C:\Users\fmeriot\.node-gyp\0.11.9\src\node.h(188): error C4430: spécificateur de typ
e manquant - int est pris en compte par défaut. Remarque : C++ ne prend pas en charg
e int par défaut [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modu
les\mmmagic\build\magic.vcxproj]
C:\Users\fmeriot\.node-gyp\0.11.9\src\node.h(189): error C4430: spécificateur de typ
e manquant - int est pris en compte par défaut. Remarque : C++ ne prend pas en charg
e int par défaut [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modu
les\mmmagic\build\magic.vcxproj]
C:\Users\fmeriot\.node-gyp\0.11.9\src\node.h(192): error C2146: erreur de syntaxe :
absence de ';' avant l'identificateur 'DecodeWrite' [C:\SVN\nodejs\sandbox\xml2json2
xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
C:\Users\fmeriot\.node-gyp\0.11.9\src\node.h(192): error C4430: spécificateur de typ
e manquant - int est pris en compte par défaut. Remarque : C++ ne prend pas en charg
e int par défaut [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modu
les\mmmagic\build\magic.vcxproj]
C:\Users\fmeriot\.node-gyp\0.11.9\src\node.h(195): error C4430: spécificateur de typ
e manquant - int est pris en compte par défaut. Remarque : C++ ne prend pas en charg
e int par défaut [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modu
les\mmmagic\build\magic.vcxproj]
..\src\magic.cc(12): error C2146: erreur de syntaxe : absence de ';' avant l'identif
icateur 'request' [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_mod
ules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(12): error C4430: spécificateur de type manquant - int est pris en c
ompte par défaut. Remarque : C++ ne prend pas en charge int par défaut [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(12): error C4430: spécificateur de type manquant - int est pris en c
ompte par défaut. Remarque : C++ ne prend pas en charge int par défaut [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(32): error C2504: 'ObjectWrap' : classe de base non définie [C:\SVN\
nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.v
cxproj]
..\src\magic.cc(54): error C4430: spécificateur de type manquant - int est pris en c
ompte par défaut. Remarque : C++ ne prend pas en charge int par défaut [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(54): error C2143: erreur de syntaxe : absence de ',' avant '&' [C:\S
VN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magi
c.vcxproj]
..\src\magic.cc(102): error C4430: spécificateur de type manquant - int est pris en
compte par défaut. Remarque : C++ ne prend pas en charge int par défaut [C:\SVN\node
js\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpr
oj]
..\src\magic.cc(102): error C2143: erreur de syntaxe : absence de ',' avant '&' [C:\
SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\mag
ic.vcxproj]
..\src\magic.cc(139): error C4430: spécificateur de type manquant - int est pris en
compte par défaut. Remarque : C++ ne prend pas en charge int par défaut [C:\SVN\node
js\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpr
oj]
..\src\magic.cc(139): error C2143: erreur de syntaxe : absence de ',' avant '&' [C:\
SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\mag
ic.vcxproj]
..\src\magic.cc(184): error C2061: erreur de syntaxe : identificateur 'uv_work_t' [C
:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\m
agic.vcxproj]
..\src\magic.cc(222): error C2061: erreur de syntaxe : identificateur 'uv_work_t' [C
:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\m
agic.vcxproj]
..\src\magic.cc(261): error C4430: spécificateur de type manquant - int est pris en
compte par défaut. Remarque : C++ ne prend pas en charge int par défaut [C:\SVN\node
js\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpr
oj]
..\src\magic.cc(261): error C2143: erreur de syntaxe : absence de ',' avant '&' [C:\
SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\mag
ic.vcxproj]
..\src\magic.cc(55): error C2248: 'v8::HandleScope::HandleScope' : impossible d'accé
der à private membre déclaré(e) dans la classe 'v8::HandleScope' [C:\SVN\nodejs\sand
box\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
          C:\Users\fmeriot\.node-gyp\0.11.9\deps\v8\include\v8.h(768) : voir la décl
  aration de 'v8::HandleScope::HandleScope'
          C:\Users\fmeriot\.node-gyp\0.11.9\deps\v8\include\v8.h(743) : voir la décl
  aration de 'v8::HandleScope'
..\src\magic.cc(64): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(64): error C2228: la partie gauche de '.IsConstructCall' doit avoir
un class/struct/union [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node
_modules\mmmagic\build\magic.vcxproj]
          le type est ''unknown-type''
..\src\magic.cc(70): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(70): error C2228: la partie gauche de '.Length' doit avoir un class/
struct/union [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\
mmmagic\build\magic.vcxproj]
          le type est ''unknown-type''
..\src\magic.cc(71): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(71): error C2227: la partie gauche de '->IsInt32' doit pointer vers
un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_module
s\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(72): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(72): error C2227: la partie gauche de '->Int32Value' doit pointer ve
rs un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_mod
ules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(79): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(79): error C2228: la partie gauche de '.Length' doit avoir un class/
struct/union [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\
mmmagic\build\magic.vcxproj]
          le type est ''unknown-type''
..\src\magic.cc(80): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(80): error C2227: la partie gauche de '->IsString' doit pointer vers
 un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_modul
es\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(82): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(82): error C2227: la partie gauche de '->ToString' doit pointer vers
 un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_modul
es\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(84): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(84): error C2227: la partie gauche de '->IsInt32' doit pointer vers
un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_module
s\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(85): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(85): error C2227: la partie gauche de '->Int32Value' doit pointer ve
rs un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_mod
ules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(86): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(86): error C2227: la partie gauche de '->IsBoolean' doit pointer ver
s un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_modu
les\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(86): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(86): error C2227: la partie gauche de '->BooleanValue' doit pointer
vers un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_m
odules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(96): error C2039: 'Wrap' : n'est pas membre de 'Magic' [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
          ..\src\magic.cc(32) : voir la déclaration de 'Magic'
..\src\magic.cc(96): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(96): error C2228: la partie gauche de '.This' doit avoir un class/st
ruct/union [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mm
magic\build\magic.vcxproj]
          le type est ''unknown-type''
..\src\magic.cc(97): error C2039: 'Ref' : n'est pas membre de 'Magic' [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
          ..\src\magic.cc(32) : voir la déclaration de 'Magic'
..\src\magic.cc(99): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(99): error C2228: la partie gauche de '.This' doit avoir un class/st
ruct/union [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mm
magic\build\magic.vcxproj]
          le type est ''unknown-type''
..\src\magic.cc(103): error C2248: 'v8::HandleScope::HandleScope' : impossible d'acc
éder à private membre déclaré(e) dans la classe 'v8::HandleScope' [C:\SVN\nodejs\san
dbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
          C:\Users\fmeriot\.node-gyp\0.11.9\deps\v8\include\v8.h(768) : voir la décl
  aration de 'v8::HandleScope::HandleScope'
          C:\Users\fmeriot\.node-gyp\0.11.9\deps\v8\include\v8.h(743) : voir la décl
  aration de 'v8::HandleScope'
..\src\magic.cc(104): error C2653: 'ObjectWrap' : n'est pas un nom de classe ni d'es
pace de noms [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\
mmmagic\build\magic.vcxproj]
..\src\magic.cc(104): error C2065: 'Unwrap' : identificateur non déclaré [C:\SVN\nod
ejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxp
roj]
..\src\magic.cc(104): error C2275: 'Magic' : utilisation non conforme de ce type com
me expression [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules
\mmmagic\build\magic.vcxproj]
..\src\magic.cc(104): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(104): error C2228: la partie gauche de '.This' doit avoir un class/s
truct/union [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\m
mmagic\build\magic.vcxproj]
          le type est ''unknown-type''
..\src\magic.cc(106): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(106): error C2227: la partie gauche de '->IsString' doit pointer ver
s un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_modu
les\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(110): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(110): error C2227: la partie gauche de '->IsFunction' doit pointer v
ers un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_mo
dules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(115): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(117): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(117): error C2227: la partie gauche de '->ToString' doit pointer ver
s un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_modu
les\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(122): error C2039: 'request' : n'est pas membre de 'Baton' [C:\SVN\n
odejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vc
xproj]
          ..\src\magic.cc(11) : voir la déclaration de 'Baton'
..\src\magic.cc(122): error C2228: la partie gauche de '.data' doit avoir un class/s
truct/union [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\m
mmagic\build\magic.vcxproj]
..\src\magic.cc(123): error C2660: 'v8::Persistent<T>::New' : la fonction ne prend p
as 1 arguments [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_module
s\mmmagic\build\magic.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\magic.cc(131): error C2039: 'request' : n'est pas membre de 'Baton' [C:\SVN\n
odejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vc
xproj]
          ..\src\magic.cc(11) : voir la déclaration de 'Baton'
..\src\magic.cc(133): error C2065: 'uv_after_work_cb' : identificateur non déclaré [
C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\
magic.vcxproj]
..\src\magic.cc(133): error C2143: erreur de syntaxe : absence de ')' avant 'Magic::
DetectAfter' [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\
mmmagic\build\magic.vcxproj]
..\src\magic.cc(130): error C3861: 'uv_queue_work' : identificateur introuvable [C:\
SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\mag
ic.vcxproj]
..\src\magic.cc(130): error C3861: 'uv_default_loop' : identificateur introuvable [C
:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\m
agic.vcxproj]
..\src\magic.cc(133): error C2059: erreur de syntaxe : ')' [C:\SVN\nodejs\sandbox\xm
l2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(140): error C2248: 'v8::HandleScope::HandleScope' : impossible d'acc
éder à private membre déclaré(e) dans la classe 'v8::HandleScope' [C:\SVN\nodejs\san
dbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
          C:\Users\fmeriot\.node-gyp\0.11.9\deps\v8\include\v8.h(768) : voir la décl
  aration de 'v8::HandleScope::HandleScope'
          C:\Users\fmeriot\.node-gyp\0.11.9\deps\v8\include\v8.h(743) : voir la décl
  aration de 'v8::HandleScope'
..\src\magic.cc(141): error C2653: 'ObjectWrap' : n'est pas un nom de classe ni d'es
pace de noms [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\
mmmagic\build\magic.vcxproj]
..\src\magic.cc(141): error C2065: 'Unwrap' : identificateur non déclaré [C:\SVN\nod
ejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxp
roj]
..\src\magic.cc(141): error C2275: 'Magic' : utilisation non conforme de ce type com
me expression [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules
\mmmagic\build\magic.vcxproj]
..\src\magic.cc(141): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(141): error C2228: la partie gauche de '.This' doit avoir un class/s
truct/union [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\m
mmagic\build\magic.vcxproj]
          le type est ''unknown-type''
..\src\magic.cc(143): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(143): error C2228: la partie gauche de '.Length' doit avoir un class
/struct/union [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules
\mmmagic\build\magic.vcxproj]
          le type est ''unknown-type''
..\src\magic.cc(147): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(151): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(151): error C2227: la partie gauche de '->IsFunction' doit pointer v
ers un type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_mo
dules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(156): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(160): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(166): error C2039: 'request' : n'est pas membre de 'Baton' [C:\SVN\n
odejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vc
xproj]
          ..\src\magic.cc(11) : voir la déclaration de 'Baton'
..\src\magic.cc(166): error C2228: la partie gauche de '.data' doit avoir un class/s
truct/union [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\m
mmagic\build\magic.vcxproj]
..\src\magic.cc(167): error C2660: 'v8::Persistent<T>::New' : la fonction ne prend p
as 1 arguments [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_module
s\mmmagic\build\magic.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\magic.cc(176): error C2039: 'request' : n'est pas membre de 'Baton' [C:\SVN\n
odejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vc
xproj]
          ..\src\magic.cc(11) : voir la déclaration de 'Baton'
..\src\magic.cc(178): error C2065: 'uv_after_work_cb' : identificateur non déclaré [
C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\
magic.vcxproj]
..\src\magic.cc(178): error C2143: erreur de syntaxe : absence de ')' avant 'Magic::
DetectAfter' [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\
mmmagic\build\magic.vcxproj]
..\src\magic.cc(175): error C3861: 'uv_queue_work' : identificateur introuvable [C:\
SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\mag
ic.vcxproj]
..\src\magic.cc(175): error C3861: 'uv_default_loop' : identificateur introuvable [C
:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\m
agic.vcxproj]
..\src\magic.cc(178): error C2059: erreur de syntaxe : ')' [C:\SVN\nodejs\sandbox\xm
l2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
..\src\magic.cc(185): error C2065: 'req' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(185): error C2227: la partie gauche de '->data' doit pointer vers un
 type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\
gps-util\node_modules\mmmagic\build\magic.vcxproj]
          le type est ''unknown-type''
..\src\magic.cc(190): error C3861: 'uv_strerror' : identificateur introuvable [C:\SV
N\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic
.vcxproj]
..\src\magic.cc(191): error C3861: 'uv_last_error' : identificateur introuvable [C:\
SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\mag
ic.vcxproj]
..\src\magic.cc(191): error C3861: 'uv_default_loop' : identificateur introuvable [C
:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\m
agic.vcxproj]
..\src\magic.cc(223): error C2248: 'v8::HandleScope::HandleScope' : impossible d'acc
éder à private membre déclaré(e) dans la classe 'v8::HandleScope' [C:\SVN\nodejs\san
dbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
          C:\Users\fmeriot\.node-gyp\0.11.9\deps\v8\include\v8.h(768) : voir la décl
  aration de 'v8::HandleScope::HandleScope'
          C:\Users\fmeriot\.node-gyp\0.11.9\deps\v8\include\v8.h(743) : voir la décl
  aration de 'v8::HandleScope'
..\src\magic.cc(224): error C2065: 'req' : identificateur non déclaré [C:\SVN\nodejs
\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj
]
..\src\magic.cc(224): error C2227: la partie gauche de '->data' doit pointer vers un
 type class/struct/union/générique [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\
gps-util\node_modules\mmmagic\build\magic.vcxproj]
          le type est ''unknown-type''
..\src\magic.cc(234): error C2819: le type 'v8::Persistent<T>' n'a pas d'opérateur '
operator ->' de membre surchargé [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gp
s-util\node_modules\mmmagic\build\magic.vcxproj]
          with
          [
              T=v8::Function
          ]
          voulez-vous utiliser '.' à la place ?
..\src\magic.cc(234): error C2039: 'Call' : n'est pas membre de 'v8::Persistent<T>'
[C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build
\magic.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\magic.cc(240): error C2661: 'v8::Local<T>::New' : aucune fonction surchargée
ne nécessite 1 arguments [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\n
ode_modules\mmmagic\build\magic.vcxproj]
          with
          [
              T=v8::Value
          ]
..\src\magic.cc(243): error C2661: 'v8::Local<T>::New' : aucune fonction surchargée
ne nécessite 1 arguments [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\n
ode_modules\mmmagic\build\magic.vcxproj]
          with
          [
              T=v8::Value
          ]
..\src\magic.cc(250): error C2819: le type 'v8::Persistent<T>' n'a pas d'opérateur '
operator ->' de membre surchargé [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gp
s-util\node_modules\mmmagic\build\magic.vcxproj]
          with
          [
              T=v8::Function
          ]
          voulez-vous utiliser '.' à la place ?
..\src\magic.cc(250): error C2039: 'Call' : n'est pas membre de 'v8::Persistent<T>'
[C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build
\magic.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\magic.cc(262): error C2248: 'v8::HandleScope::HandleScope' : impossible d'acc
éder à private membre déclaré(e) dans la classe 'v8::HandleScope' [C:\SVN\nodejs\san
dbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxproj]
          C:\Users\fmeriot\.node-gyp\0.11.9\deps\v8\include\v8.h(768) : voir la décl
  aration de 'v8::HandleScope::HandleScope'
          C:\Users\fmeriot\.node-gyp\0.11.9\deps\v8\include\v8.h(743) : voir la décl
  aration de 'v8::HandleScope'
..\src\magic.cc(267): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(267): error C2228: la partie gauche de '.Length' doit avoir un class
/struct/union [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules
\mmmagic\build\magic.vcxproj]
          le type est ''unknown-type''
..\src\magic.cc(267): error C2065: 'args' : identificateur non déclaré [C:\SVN\nodej
s\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic\build\magic.vcxpro
j]
..\src\magic.cc(267): fatal error C1003: le nombre d'erreurs est supérieur à 100 ; a
rrêt de la compilation [C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\nod
e_modules\mmmagic\build\magic.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:101:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:827:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\SVN\nodejs\sandbox\xml2json2xml\node_modules\gps-util\node_modules\mmmagic
gyp ERR! node -v v0.11.9
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok

> xmlbuilder@2.1.0 prepublish c:\Users\fmeriot\AppData\Local\Temp\npm-9188-k3FU4Anp\xmlbuilder-2.1.01389781168564-0.07151282206177711\package
> coffee -co lib/ src/*.coffee

'coffee' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
npm ERR! addLocalDirectory Could not pack "c:\\Users\\fmeriot\\AppData\\Local\\Temp\\npm-9188-k3FU4Anp\\xmlbuilder-2.1.01389781168564-0.07151282206177711\\package" to "C:\\Users\\fmeriot\\AppData\\Roaming\\npm-cache\\xmlbuilder\\2.1.0\\package.tgz"
npm ERR! xmlbuilder@2.1.0 prepublish: `coffee -co lib/ src/*.coffee`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xmlbuilder@2.1.0 prepublish script.
npm ERR! This is most likely a problem with the xmlbuilder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee -co lib/ src/*.coffee
npm ERR! You can get their info via:
npm ERR!     npm owner ls xmlbuilder
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gps-util"
npm ERR! cwd C:\SVN\nodejs\sandbox\xml2json2xml
npm ERR! node -v v0.11.9
npm ERR! npm -v 1.3.15
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\SVN\nodejs\sandbox\xml2json2xml\npm-debug.log
npm ERR! not ok code 0

**Comment by vanng822** [comment]
v0.1.0 should now run on node v0.12
