### ISSUE TITLE
Node 4.x install error

### ISSUE THREAD

**Issue by alexdonei** [vanng822/gps-util#4]
I have a problem when I try to install this module in NodeJS 4.3.0 and 4.4.1 (npm -v 2.14.12 and 2.14.20) on Mac Os X and Linux

1081 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gps-util" "--save"
1082 error node v4.4.1
1083 error npm  v2.14.20
1084 error code ELIFECYCLE
1085 error mmmagic@0.3.13 install: `node-gyp rebuild`
1085 error Exit status 1
1086 error Failed at the mmmagic@0.3.13 install script 'node-gyp rebuild'.
1086 error This is most likely a problem with the mmmagic package,
1086 error not with npm itself.
1086 error Tell the author that this fails on your system:
1086 error     node-gyp rebuild
1086 error You can get information on how to open an issue for this project with:
1086 error     npm bugs mmmagic
1086 error Or if that isn't available, you can get their info via:
1086 error
1086 error     npm owner ls mmmagic
1086 error There is likely additional logging output above.

It's sound like an error when try to install the dependencies mmmagic@0.3.13, if I try to install mmmagic the version installed is 0.4.1 and the installation work fine.

**Comment by vanng822** [comment]
I tried to upgrade mmmagic but the tests failed
https://travis-ci.org/vanng822/gps-util

Maybe time to find a package for replacing mmmagic. The only function we use there is type inspection. I couldn't find any pure javascript package that did well this job by that time. Should be some these days.

**Comment by vanng822** [comment]
I removed mmmagic which means that those functions bellow will not check the content type
tcxParseFile
tcxParseURL
gpxParseFile
gpxParseURL
Make sure trust your source or write a wrapper and inspect the content
