### ISSUE TITLE
gpxParse for file without time attributes

### ISSUE THREAD

**Issue by alexdonei** [vanng822/gps-util#7]
Hi,
When i try to parse a GPX file downloaded by Strava like track, no one point found.
I have check the file GPX and the code inside gpx-parse.js and I found this problem:
when the code is analyzing a point, check if the point has the time attribute, but in my file this attribute is not present.
I resolved locally by creating a new module, gpxParseTrack, that call an internal function that not check the presence of attributes time.

Why you check the presence of the time attibute?
You can modify the library to check the file GPX without this attibute? Maybe as an option.
Thank you

**Comment by vanng822** [comment]
Don't remember exact but I guess we can make it optional. Parse only if it is there

**Comment by vanng822** [comment]
@alexdonei it should be fixed in v1.0.1 Try it out.

I needed it for showing the timeline but look like optional in the spec v1.1

**Comment by alexdonei** [comment]
Works, great!
Thank you!
Alex
